version: '3.8'

services:
  magi-server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount Hugging Face cache directory to persist models
      - huggingface_cache:/root/.cache/huggingface
    environment:
      # Set Hugging Face cache directory
      - HF_HOME=/root/.cache/huggingface
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
      # Optional: Set offline mode after first download
      # - TRANSFORMERS_OFFLINE=1
    restart: unless-stopped

volumes:
  # Named volume to persist Hugging Face models
  huggingface_cache:
    driver: local